# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.1.0"

default_platform :ios


platform :ios do

  before_all do
    xctest(
      #scheme: ‘FingerLockTests’,
      destination: "platform=iOS Simulator,name=iPhone 6,OS=8.3",
      clean: nil
    )
  end

  desc "Runs all the tests"
  lane :test do
    snapshot
    frameit
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    snapshot
    frameit
    sigh
    ipa(
      scheme: “FingerLock”
    )
    deliver #(
      #skip_deploy: true,
    #  beta: true
    #)
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    snapshot
    frameit
    sigh
    deliver#(
     # skip_deploy:true,
     # force:true
    #)
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end

end